[package]
name = "delta"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.41"
clap = {version = "4.5.36", features = ["derive"]}
flate2 = "1.1.1"
glob = "0.3.2"
hex = "0.4.3"
indexmap = "2.9.0"
ini = "1.3"
regex = "1.11.1"
sha1 = "0.10.6"
users = "0.11.0"
walkdir = "2.5.0"

