use std::fs;

use crate::{
    kvlm::KvlmKey,
    object::{DeltaObject, DeltaTag, ObjectFormat},
    repo::ObjectHash,
};
use anyhow::{anyhow, Result};
use indexmap::IndexMap;

use crate::repo::DeltaRepository;

pub fn tag(name: Option<String>, object: String, create_tag_object: bool) -> Result<()> {
    let repo = DeltaRepository::repo_find(std::env::current_dir()?)?;

    if let Some(name) = name {
        tag_create(&repo, name, object, create_tag_object)?;
    }
    Ok(())
}

fn tag_create(
    repo: &DeltaRepository,
    name: String,
    object: String,
    create_tag_object: bool,
) -> Result<()> {
    let sha = repo
        .object_find(&object, Some(ObjectFormat::Commit), true)?
        .ok_or(anyhow!("Object not found"))?;

    let sha = if create_tag_object {
        let mut tag = DeltaTag {
            data: IndexMap::new(),
        };

        let value = vec![sha.as_bytes().to_vec()];
        tag.data.insert("object".to_string(), value);

        let value = vec!["commit".as_bytes().to_vec()];
        tag.data.insert("type".to_string(), value);

        let value = vec![name.as_bytes().to_vec()];
        tag.data.insert("tag".to_string(), value);

        let value = vec!["seven".as_bytes().to_vec()];
        tag.data.insert("tagger".to_string(), value);

        let key = KvlmKey::Message.as_str().to_string();
        let value = vec!["A tag generated by delta".as_bytes().to_vec()];
        tag.data.insert(key, value);

        let tag = DeltaObject::Tag(tag);
        repo.object_write(&tag)?;
        let ObjectHash { sha, payload: _ } = DeltaRepository::compute_object_hash(&tag)?;
        sha
    } else {
        sha
    };

    ref_create(repo, format!("tags/{}", name), sha)?;
    Ok(())
}

fn ref_create(repo: &DeltaRepository, ref_name: String, sha: String) -> Result<()> {
    let file = repo.repo_file(&["refs", &ref_name], true)?;
    fs::write(file, sha)?;
    Ok(())
}
